<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    let mes = "wrong";
    Promise.reject(mes).then(null,function(e){
        console.log(e);   //wrong
        console.log(e===mes);//true
    })

    //Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数。
    // 这一点与Promise.resolve方法不一致
    const thenable = {
        then(resolve, reject) {
            reject('出错了');
        }
    };

    Promise.reject(thenable)
            .catch(e => {
        console.log(e === thenable); // true
    });
</script>
</body>
</html>