<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    // promise 中返回promise --实例2

    test1(); //


    function test1() {
        const p1 = new Promise(function (resolve, reject) {
            setTimeout(function () {
                reject(new Error("fail"));

            }, 1000)
        })
        const p2 = new Promise(function (resolve, reject) {
            setTimeout(
                () => resolve(p1),
                300);
            //p1的状态就会传递给p2，p1的状态决定了p2的状态，3000ms后（并非100ms）才执行p2

        })


        p2
            .then(function(result){
                console.log(result);
            }).catch(function(err){
            console.log(err);
        });



        /*
         p2 中定时器延迟时间 < p1 定时器中延迟时间，输出：

         Error: fail at promise7-promise注意4.html:20
         */

        /*
         p2 中定时器延迟时间 > p1 定时器中延迟时间，输出：
         Uncaught (in promise) Error: fail at promise9.html:11， 然后变为
         Error: fail  at promise7-promise注意4.html:20
         */
    }



    

</script>
</body>
</html>